### ISSUE TITLE
可以支持NATS的消息列队桥接吗

### ISSUE THREAD

**Issue by accaolei** [rmqtt/rmqtt#101]
可以支持NATS的消息列队桥接吗，将MQTT的消息转到NATS的stream中

**Comment by bittcrafter** [comment]
可以的，您应该对NATS比较熟悉，具体还有什么特殊需求吗？

**Comment by accaolei** [comment]
感谢，您很Nice。
没有特殊要求了，主要是需要能将MQTT消息转到NATS JetStream的某个stream中。可做持久化数据，也可以作为后续进行异步处理

**Comment by bittcrafter** [comment]
此功能已经实现，如果要提前使用须自行通过源码编译，此功能有关配置可参见： https://github.com/rmqtt/rmqtt/blob/master/docs/zh_CN/bridge-egress-nats.md

**Comment by accaolei** [comment]
感谢，我去测试一下

**Comment by accaolei** [comment]
测试可以正常使用，感谢。

**Comment by bittcrafter** [comment]
> 测试可以正常使用，感谢。

OK
