### ISSUE TITLE
怎么样设置通过账号密码才能连接服务端的

### ISSUE THREAD

**Issue by qcjxberin** [rmqtt/rmqtt#11]
怎么样设置通过账号密码才能连接服务端的

**Comment by rhello2999** [comment]
启用rmqtt-auth-http插件，需要自己实现一套http auth服务，需要实现的api参照：https://github.com/rmqtt/rmqtt/blob/master/rmqtt-plugins/rmqtt-auth-http.toml

**Comment by qcjxberin** [comment]
这个链接有看过，这个是要怎么启用rmqtt-auth-http插件呢？是要实现里面的那些接口吗？

**Comment by rmqtt** [comment]
rmqtt.toml配置文件里打开rmqtt-auth-http：
startedplugins.default_startups = [
# "rmqtt-auth-http",
# "rmqtt-web-hook",
# "rmqtt-cluster-broadcast",
# "rmqtt-cluster-raft",
# "rmqtt-http-api"
]
插件配置文件里的几个api都需要实现。







---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月27日 21:18 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [rmqtt/rmqtt] 怎么样设置通过账号密码才能连接服务端的 (Issue #11) |

这个链接有看过，这个是要怎么启用rmqtt-auth-http插件呢？是要实现里面的那些接口吗？

**Comment by qcjxberin** [comment]
好的，我试试，你的这个库在Rust里是功能最强大的，加油。

**Comment by rhello2999** [comment]
> 好的，我试试，你的这个库在Rust里是功能最强大的，加油。

谢谢您对RMQTT的肯定和关注，加油，:)

**Comment by qcjxberin** [comment]
这几个接口返回的数据格式是什么样的？

**Comment by rmqtt** [comment]
http状态码返回是200就是成功，如果须要对结果在本次连接中缓存就在body中放一个字符串ignore



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月28日 06:46 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [rmqtt/rmqtt] 怎么样设置通过账号密码才能连接服务端的 (Issue #11) |

这几个接口返回的数据格式是什么样的？

**Comment by qcjxberin** [comment]
谢谢，辛苦了，周末还打扰你

**Comment by jvasile** [comment]
[Fossil comment by james]

[GitHub comment by rhello2999]

启用rmqtt-auth-http插件，需要自己实现一套http auth服务，需要实现的api参照：https://github.com/rmqtt/rmqtt/blob/master/rmqtt-plugins/rmqtt-auth-http.toml

**Comment by jvasile** [comment]
[Fossil comment by james]

[GitHub comment by qcjxberin]

这个链接有看过，这个是要怎么启用rmqtt-auth-http插件呢？是要实现里面的那些接口吗？

**Comment by jvasile** [comment]
[Fossil comment by james]

[GitHub comment by ]

rmqtt.toml配置文件里打开rmqtt-auth-http：
startedplugins.default_startups = [
# "rmqtt-auth-http",
# "rmqtt-web-hook",
# "rmqtt-cluster-broadcast",
# "rmqtt-cluster-raft",
# "rmqtt-http-api"
]
插件配置文件里的几个api都需要实现。







---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月27日 21:18 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [rmqtt/rmqtt] 怎么样设置通过账号密码才能连接服务端的 (Issue #11) |

这个链接有看过，这个是要怎么启用rmqtt-auth-http插件呢？是要实现里面的那些接口吗？

**Comment by jvasile** [comment]
[Fossil comment by james]

[GitHub comment by qcjxberin]

好的，我试试，你的这个库在Rust里是功能最强大的，加油。

**Comment by jvasile** [comment]
[Fossil comment by james]

[GitHub comment by rhello2999]

> 好的，我试试，你的这个库在Rust里是功能最强大的，加油。

谢谢您对RMQTT的肯定和关注，加油，:)

**Comment by jvasile** [comment]
[Fossil comment by james]

[GitHub comment by qcjxberin]

这几个接口返回的数据格式是什么样的？

**Comment by jvasile** [comment]
[Fossil comment by james]

[GitHub comment by ]

0.2.11 对rmqtt-auth-http做了些调整，具体可参照：https://github.com/rmqtt/rmqtt/releases/tag/0.2.11 、https://github.com/rmqtt/rmqtt/blob/master/rmqtt-plugins/rmqtt-auth-http.toml 和 https://github.com/rmqtt/templates/tree/main/rmqtt-auth-http-server



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月28日 06:46 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [rmqtt/rmqtt] 怎么样设置通过账号密码才能连接服务端的 (Issue #11) |

这几个接口返回的数据格式是什么样的？

**Comment by jvasile** [comment]
[Fossil comment by james]

[GitHub comment by qcjxberin]

谢谢，辛苦了，周末还打扰你
