### ISSUE TITLE
请教如何基于这个库开发一些功能

### ISSUE THREAD

**Issue by 18601673727** [rmqtt/rmqtt#12]
小白看了文档感觉有点蒙蒙的，具体来说这个库的应用场景是什么呢？如何集成到现有的Rust项目中去？比如我的tokio consumer要做一个job，完成之后再把结果publish到broker去，broker自动通知producer这个job完成了，这个逻辑用rmqtt该怎样实现呢？另外broker应该怎样部署？每隔一段时间重复执行一个job怎样实现？

**Comment by rhello2999** [comment]
你好，建议先直接使用docker来运行rmqtt broker，比如：
`docker run -d --name rmqtt -p 1883:1883 -p 8883:8883 -p 11883:11883 -p 6060:6060 -v /app/log/rmqtt:/var/log/rmqtt  rmqtt/rmqtt:latest`

然后可以使用MQTTBox、MQTT.fx等MQTT客户端工具来测试连接/订阅/发布消息。

在你现有的rust项目中，可以使用 [paho.mqtt.rust](https://github.com/eclipse/paho.mqtt.rust) 或 [ntex-mqtt](https://github.com/ntex-rs/ntex-mqtt) MQTT 客户端来连接/订阅/发布消息。

**Comment by 18601673727** [comment]
好的 非常感谢！
