### ISSUE TITLE
Apache Pulsar Bridging - Ingress Mode

### ISSUE THREAD

**Issue by cosoc** [rmqtt/rmqtt#121]
该模式rmqtt可以订阅多个不同的pulsr主题，并根据约定的数据结构解析分发消息

pulsr主题中的消息格式必须遵循如下格式：
```json
{
   "topics": [
       "a", "b" // 动态指定的目标主题
   ],
   "qos": 1, // 服务质量 (Quality of Service) 设置
   "msg": "hello rmqtt" // 消息内容
}

```

可以实现么？目前不太熟悉rmqtt的代码，铁子可以快速实现么？拜谢 

配置文件

[[bridges]]
enable = true
name = "bridge_pulsar_1"
servers = "pulsar://127.0.0.1:6650"

[[bridges.entries]]
remote.topic = "non-persistent://public/default/device2"
[[bridges.entries]]
remote.topic = "non-persistent://public/default/device1"

**Comment by bittcrafter** [comment]
Hi, 你们的业务的确有从Apache Pulsar中订阅消息吗？

**Comment by cosoc** [comment]
> Hi, 你们的业务的确有从Apache Pulsar中订阅消息吗？

是的，我们是物联网行业，消息非常多，系统构成复杂，所有出口消息目前是从pulsar中获取后专门的程序再发给mqtt代理给设备或者其他服务的，这一层消息转发非常适合在mqtt代理端处理是最合理的。

**Comment by cosoc** [comment]
![image](https://github.com/user-attachments/assets/be882460-420d-4140-a6a6-99dbadf9c28f)
我们的架构大致是这样的

**Comment by tryor** [comment]
那看来还是有必要实现通用的 Apache Pulsar Bridging - Ingress Mode插件。

**Comment by bittcrafter** [comment]
那看来还是有必要实现通用的 Apache Pulsar Bridging - Ingress Mode插件。

**Comment by bittcrafter** [comment]
你们的数据就是这种格式吗？
{
   "topics": [
       "a", "b" // 动态指定的目标主题
   ],
   "qos": 1, // 服务质量 (Quality of Service) 设置
   "msg": "hello rmqtt" // 消息内容
}

我现在实现了个把topics、qos等数据放到Properties的版本。

**Comment by cosoc** [comment]
> 你们的数据就是这种格式吗？ { "topics": [ "a", "b" // 动态指定的目标主题 ], "qos": 1, // 服务质量 (Quality of Service) 设置 "msg": "hello rmqtt" // 消息内容 }
> 
> 我现在实现了个把topics、qos等数据放到Properties的版本。

#[derive(Serialize, Deserialize,Clone,Debug)]
pub struct MsgDispatcherPack {
    // 该消息需要分发的mqtt broker的topic
    pub topics: Vec<String>,
    // 如果不指定,默认为0
    pub qos: Option<i16>,
    // 如果没指定，默认丢弃不处理
    pub msg: Option<String>,
}

**Comment by bittcrafter** [comment]
已经提交了一个版本的  `rmqtt-bridge-ingress-pulsar` 实现，可通过配置达到您现在的要求。
如：
```
remote.payload_format = "json"
remote.payload_path = "msg"
local.topic = "${remote.payload.topics}"
local.allow_empty_forward = false
```
