### ISSUE TITLE
Apache Pulsar 出口模式remote.ordering_key建议

### ISSUE THREAD

**Issue by cosoc** [rmqtt/rmqtt#123]
remote.ordering_key = "" 我建议改为客户端id,实践中我们都是相同的客户端消息以id作为key好保证消费的顺序性。

可以增加为一个枚举，

$(client_id) : 表示动态的获取id做为key $() 表示是一个变量值
fun:gen_random_key(10):  fun: 表示调用一个函数（已经存在的）  gen_random_key(10) 表示具体函数10是参数，这里表示随机值的长度 

默认指定一个key实际上没有任何意义

**Comment by bittcrafter** [comment]
感谢您非常好的建议
