### ISSUE TITLE
最新版本能发布一个release么？

### ISSUE THREAD

**Issue by qcjxberin** [rmqtt/rmqtt#13]
最新版本能发布一个release么？我怕生成又会遇到啥问题

**Comment by rmqtt** [comment]
最早这周末会生成一个版本0.2.11



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月02日 14:14 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [rmqtt/rmqtt] 最新版本能发布一个release么？ (Issue #13) |

最新版本能发布一个release么？我怕生成又会遇到啥问题

**Comment by qcjxberin** [comment]
收到，谢谢。
