### ISSUE TITLE
tls 和 wss 不能成功连接

### ISSUE THREAD

**Issue by en-one** [rmqtt/rmqtt#130]
你好，我最近在本地部署了rmqtt，测试后tcp 以及 ws都能正常连接
但是当我连接对应的8883端口以及8443端口时，使用mqttx工具无法连接，且终端也没有任何输入。我也无法定位到问题。
相关的配置均未修改过

**Comment by bittcrafter** [comment]
您好，我使用MQTTBox和MQTTX测试8883和8443都是成功的。

**Comment by en-one** [comment]
> 您好，我使用MQTTBox和MQTTX测试8883和8443都是成功的。

您好，我也使用了MQTTX连接可以。我想问下，我是用js代码连接的8443端口不能成功。ws协议是可以的


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MQTT Example</title>
    <script src="https://unpkg.com/mqtt/dist/mqtt.min.js"></script>
</head>
<body>
    <h1>MQTT Example</h1>
    
    <input type="text" id="messageInput" placeholder="Enter your message here...">
    <button onclick="sendMessage()">Send Message</button>

    <script>

        // const brokerUrl = 'ws://127.0.0.1:8080/mqtt'; // 本地环境mqtt
         const brokerUrl = 'wss://127.0.0.1:8443/mqtt'; // 本地环境mqtt



        // 创建一个客户端实例
        const client = mqtt.connect(brokerUrl, {
            clientId: 'client-id',
            clean: true, // 如果设置为 true，断开连接时会清除所有会话信息
            connectTimeout: 4000, // 连接超时时间
            reconnectPeriod: 4000, // 重新连接的时间间隔
            username:“username,
            password:"pass",
            useSSL: true,
            rejectUnauthorized: false,
        });

        // 连接成功时的回调
        client.on('connect', () => {
            console.log('Connected to MQTT broker');
        });

        // 收到消息时的回调
        client.on('message', (topic, message) => {
            console.log(`Received message on topic: ${topic}`);
            console.log(`Message: ${message.toString()}`);
        });

        // 连接错误时的回调
        client.on('error', (err) => {
            console.error('Connection error: ', err);
        });

        // 断开连接时的回调
        client.on('close', () => {
            console.log('Disconnected from MQTT broker');
        });

        // 发送消息的函数
        function sendMessage() {
            const message = document.getElementById('messageInput').value;
            if (message) {
                client.publish('josiah/topic', message, { qos: 1, retain: true, messageExpiryInterval: 7200 }, (err) => {
                    if (err) {
                        console.error('Failed to publish message: ', err);
                    } else {
                        console.log('Message published: ', message);
                        // 清空输入框
                        document.getElementById('messageInput').value = '';
                    }
                });
            } else {
                alert('Please enter a message.');
            }
        }
    </script>
</body>
</html>

**Comment by bittcrafter** [comment]
这个是因为证书问题，浏览器中的mqtt.js好像不能使用自签名的证书，去阿里云或其他平台申请一个短期的免费证书就可以



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年11月21日 20:55 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [rmqtt/rmqtt] tls 和 wss 不能成功连接 (Issue #130) |

您好，我使用MQTTBox和MQTTX测试8883和8443都是成功的。

您好，我也使用了MQTTX连接可以。我想问下，我是用js代码连接的8443端口不能成功。ws协议是可以的

<title>MQTT Example</title> <script src="https://unpkg.com/mqtt/dist/mqtt.min.js"></script>
MQTT Example
Send Message
<script>

    // const brokerUrl = 'ws://127.0.0.1:8080/mqtt'; // 本地环境mqtt
     const brokerUrl = 'wss://127.0.0.1:8443/mqtt'; // 本地环境mqtt



    // 创建一个客户端实例
    const client = mqtt.connect(brokerUrl, {
        clientId: 'client-id',
        clean: true, // 如果设置为 true，断开连接时会清除所有会话信息
        connectTimeout: 4000, // 连接超时时间
        reconnectPeriod: 4000, // 重新连接的时间间隔
        username:“username,
        password:"pass",
        useSSL: true,
        rejectUnauthorized: false,
    });

    // 连接成功时的回调
    client.on('connect', () => {
        console.log('Connected to MQTT broker');
    });

    // 收到消息时的回调
    client.on('message', (topic, message) => {
        console.log(`Received message on topic: ${topic}`);
        console.log(`Message: ${message.toString()}`);
    });

    // 连接错误时的回调
    client.on('error', (err) => {
        console.error('Connection error: ', err);
    });

    // 断开连接时的回调
    client.on('close', () => {
        console.log('Disconnected from MQTT broker');
    });

    // 发送消息的函数
    function sendMessage() {
        const message = document.getElementById('messageInput').value;
        if (message) {
            client.publish('josiah/topic', message, { qos: 1, retain: true, messageExpiryInterval: 7200 }, (err) => {
                if (err) {
                    console.error('Failed to publish message: ', err);
                } else {
                    console.log('Message published: ', message);
                    // 清空输入框
                    document.getElementById('messageInput').value = '';
                }
            });
        } else {
            alert('Please enter a message.');
        }
    }
</script>

**Comment by en-one** [comment]
@bittcrafter 你好，我想在问下 
external.cross_certificate = true 这个配置的作用。
是否和单向认证和双向认证有关。以及和下面的external.cert， external.key 又有什么关系

**Comment by bittcrafter** [comment]
是的，就是双向认证



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年11月22日 11:12 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [rmqtt/rmqtt] tls 和 wss 不能成功连接 (Issue #130) |

@bittcrafter 你好，我想在问下
external.cross_certificate = true 这个配置的作用。
是否和单向认证和双向认证有关。以及和下面的external.cert， external.key 又有什么关系
