### ISSUE TITLE
请开通付费赞助

### ISSUE THREAD

**Issue by tsingson** [rmqtt/rmqtt#14]
请开通付费赞助, 包括 one-time payment,   以 $ 示支持.

**Comment by rmqtt** [comment]
非常感谢您对我的开源项目的关注和建议。目前，我将项目保持为免费开源的状态，这是为了让更多的人能够使用并受益于它。我希望用户能够尽情地使用，并根据自己的具体业务需求提出宝贵的建议和意见，这对于项目的改进非常重要。

虽然我暂时不打算开通付费赞助选项，但如果您愿意，您可以通过其他方式支持我的项目。例如，您可以在社交媒体上分享我的项目，向其他人推荐它，或者为项目做一些贡献，比如提交错误报告、参与讨论或贡献代码等。这些支持对于项目的发展同样具有重要意义。

再次感谢您的建议和支持，我将继续努力改进项目，并为用户提供更好的使用体验。如果您有任何其他的问题或建议，欢迎随时与我交流。谢谢！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月05日 01:00 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [rmqtt/rmqtt] 请开通付费赞助 (Issue #14) |

请开通付费赞助, 包括 one-time payment, 以 $ 示支持.

**Comment by tsingson** [comment]
哈, 你这回答, 既然这样, 就感谢了.

国人的优秀开源项目,  我个人向来就一次给$100以示支持, 如果感觉特别好, 那就多支持几次. 

再三地, 诚挚祝头发密又长, 生活闲而愉快.
