### ISSUE TITLE
有技术社区吗

### ISSUE THREAD

**Issue by kulame** [rmqtt/rmqtt#15]
这个项目真的很不错，有专门讨论这个项目的技术群吗？

**Comment by rmqtt** [comment]
暂时还没有，之后我去建一个，感谢您的建议和支持。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月05日 20:00 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [rmqtt/rmqtt] 有技术社区吗 (Issue #15) |

这个项目真的很不错，有专门讨论这个项目的技术群吗？

**Comment by kulame** [comment]
建好了at我哈 我想加进来一起讨论
