### ISSUE TITLE
有k8s的安装示例吗

### ISSUE THREAD

**Issue by youtaqiu** [rmqtt/rmqtt#17]

**Comment by rmqtt** [comment]
暂时还没有呢！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月12日 10:52 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [rmqtt/rmqtt] 有k8s的安装示例吗 (Issue #17) |
