### ISSUE TITLE
请教一下，有没有批量发布的接口？怎么调用？

### ISSUE THREAD

**Issue by saywol** [rmqtt/rmqtt#21]
请教一下，有没有批量发布的接口？怎么调用？

**Comment by rmqtt** [comment]
看看这个API是不是您想要的：https://github.com/rmqtt/rmqtt/blob/master/docs/zh_CN/http-api.md#post-apiv1mqttpublish



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月13日 15:25 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [rmqtt/rmqtt] 请教一下，有没有批量发布的接口？怎么调用？ (Issue #21) |

请教一下，有没有批量发布的接口？怎么调用？

**Comment by saywol** [comment]
谢谢您的光速回复，我仔细研究了文档，但是似乎并不像我希望的那样的，或许我应该具体描述一下我的需求场景：我的场景是有一个高速的数据源，有若干个要订阅的客户机。这个高速数据源每秒会产生几十万个数据，我如果一条一条地发布，那性能是不能满足的。所以我希望的是一个批量的发布，可以让我以
'{"topic":"foo/1","payload":"Hello World","qos":1,"retain":false}{"topic":"foo/1","payload":"Hello World","qos":1,"retain":false}{"topic":"foo/1","payload":"Hello World","qos":1,"retain":false}'
这样N条一个请求发布出去，甚至不要用json，而是直接按顺序地写属性，比如{"foo/1","Hello World",1,0}{"foo/2","Hello World",1,0}这样更能节省珍贵的网络带宽。

**Comment by rmqtt** [comment]
根据您对业务场景的描述，我认为可创建多个MQTT客户端来发布消息，不会比使用HTTP API一次提交多个消息的速度慢。如果您有条件，可以针对这个业务场景做一次压力测试。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月14日 00:50 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [rmqtt/rmqtt] 请教一下，有没有批量发布的接口？怎么调用？ (Issue #21) |

谢谢您的光速回复，我仔细研究了文档，但是似乎并不像我希望的那样的，或许我应该具体描述一下我的需求场景：我的场景是有一个高速的数据源，有若干个要订阅的客户机。这个高速数据源每秒会产生几十万个数据，我如果一条一条地发布，那性能是不能满足的。所以我希望的是一个批量的发布，可以让我以
'{"topic":"foo/1","payload":"Hello World","qos":1,"retain":false}{"topic":"foo/1","payload":"Hello World","qos":1,"retain":false}{"topic":"foo/1","payload":"Hello World","qos":1,"retain":false}'
这样N条一个请求发布出去，甚至不要用json，而是直接按顺序地写属性，比如{"foo/1","Hello World",1,0}{"foo/2","Hello World",1,0}这样更能节省珍贵的网络带宽。

**Comment by timzaak** [comment]
确实如此，就是不确定 @saywol 有无在服务器端引入 Mqtt 客户端的条件
