### ISSUE TITLE
打包的文件大小是否能压缩小的？

### ISSUE THREAD

**Issue by qcjxberin** [rmqtt/rmqtt#22]
打包的文件大小是否能压缩小的？

**Comment by rmqtt** [comment]
可以研究下这个 https://github.com/upx/upx/releases



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月21日 12:33 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [rmqtt/rmqtt] 打包的文件大小是否能压缩小的？ (Issue #22) |

打包的文件大小是否能压缩小的？
