### ISSUE TITLE
[Question] if auth/acl http callback error message can be sent to client？

### ISSUE THREAD

**Issue by timzaak** [rmqtt/rmqtt#23]
If should  I create topic which publish the error message for auth/acl？

是否必须通过创建一个专门用来发布 认证/授权 错误信息的主题来解决这个问题？

**Comment by rmqtt** [comment]
暂时只能查看日志等手段获取异常情况。之后会考虑$SYS主题，来收集各种broker内部事件。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月25日 10:47 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [rmqtt/rmqtt] [Question] if auth/acl http callback error message can be sent to client？ (Issue #23) |

If should I create topic which publish the error message for auth/acl？

是否必须通过创建一个专门用来发布 认证/授权 错误信息的主题来解决这个问题？
