### ISSUE TITLE
http-api fails in firefox script => Reason: CORS header ‘Access-Control-Allow-Origin’ missing

### ISSUE THREAD

**Issue by greenpdx** [rmqtt/rmqtt#24]
I am writing a vue/axios interface to the http-api,  rmqtt send the data just fine( status 200), but firefox does not allow the data to script because  CORS header ‘Access-Control-Allow-Origin’ missing.

I can turn it off in firefox by [about:config](https://about:config) about:config -> security.fileuri.strict_origin_policy -> false
But this is a security issue.

I looked at the http-api code but could not find where the headers are set.

How do I add Access-Control-Allow-Origin: *

**Comment by akrpic77** [comment]
Usually one would put reverse proxy in front of both, the page and the http/websocket mqtt server (no CORS problem. If you are using vite check out [built in proxy](https://vitejs.dev/config/server-options.html#server-proxy).

**Comment by greenpdx** [comment]
I am developing in a container on a host, using the browser on a thrid host and the  rmqtt server is running on a RPi all on the same network, and the container is running in a nat of a host.
I could put a nginx server on the RPi and proxy the web app through that proxy.
I proxy from vite to http-api on the Rpi  it is the same  origin 
      proxy: {
      '/api': {
        target: 'http://192.168.42.34:6060',
        changeOrigin: true,
        rewrite: (path) => path.replace(/^\/api/, '/api\/v1/'),
      }
    },
And it works
