### ISSUE TITLE
/mqtt/subscribe Not Found

### ISSUE THREAD

**Issue by greenpdx** [rmqtt/rmqtt#25]
I have nodes, broker,clients,subscriptions, routes and publish working, but subscribe returns a 404. I have tried it from a browser using axios and curl.  I have used tcpdump to verify the the request on the wire. 

I get the error "session does not exist", not sure what this means.  

I am using mqttx client and I can subscribe and publish with no problem on port 1883.

http://10.1.42.157:3000/api/mqtt/subscribe
detail | "session does not exist"

 curl -i -X POST "http://192.168.42.34:6060/api/v1/mqtt/subscribe" --header 'Content-Type: application/json' -d '{"topic":"testtopic/#","clientid":"6"}'
HTTP/1.1 404 Not Found
content-type: text/html
content-length: 912
date: Wed, 28 Jun 2023 10:15:04 GMT

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>404: Not Found</title>
    <style>
    :root {
        --bg-color: #fff;
        --text-color: #222;
    }
    body {
        background: var(--bg-color);
        color: var(--text-color);
        text-align: center;
    }
    footer{text-align:center;}
    @media (prefers-color-scheme: dark) {
        :root {
            --bg-color: #222;
            --text-color: #ddd;
        }
        a:link { color: red; }
        a:visited { color: #a8aeff; }
        a:hover {color: #a8aeff;}
        a:active {color: #a8aeff;}
    }
    </style>
</head>
<body>
    <div>
        <h1>404: Not Found</h1><h3>The requested resource could not be found.</h3><p>session does not exist</p><hr />
        <footer><a href="https://salvo.rs" target="_blank">salvo</a></footer>
    </div>
</body>
</html>

**Comment by rmqtt** [comment]
The MQTT client ID does not exist. That is, '6' does not exist.



---- Replied Message ----
| From | Shaun ***@***.***> |
| Date | 06/28/2023 18:42 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [rmqtt/rmqtt] /mqtt/subscribe Not Found (Issue #25) |

I have nodes, broker,clients,subscriptions, routes and publish working, but subscribe returns a 404. I have tried it from a browser using axios and curl. I have used tcpdump to verify the the request on the wire.

I get the error "session does not exist", not sure what this means.

I am using mqttx client and I can subscribe and publish with no problem on port 1883.

http://10.1.42.157:3000/api/mqtt/subscribe
detail | "session does not exist"

curl -i -X POST "http://192.168.42.34:6060/api/v1/mqtt/subscribe" --header 'Content-Type: application/json' -d '{"topic":"testtopic/#","clientid":"6"}'
HTTP/1.1 404 Not Found
content-type: text/html
content-length: 912
date: Wed, 28 Jun 2023 10:15:04 GMT

<title>404: Not Found</title> <style> :root { --bg-color: #fff; --text-color: #222; } body { background: var(--bg-color); color: var(--text-color); text-align: center; } footer{text-align:center;} @media (prefers-color-scheme: dark) { :root { --bg-color: #222; --text-color: #ddd; } a:link { color: red; } a:visited { color: #a8aeff; } a:hover {color: #a8aeff;} a:active {color: #a8aeff;} } </style>
404: Not Found
The requested resource could not be found.

session does not exist

salvo

**Comment by greenpdx** [comment]
Thank you, putting a existing client, it responds.
What is the purpose of this command?  It does not block and wait for a publish, it replies 'true' to all topics.

**Comment by rmqtt** [comment]
This API can help clients subscribe to topics. It can be used to solve the situation where the client device cannot update but needs to subscribe to new topics.



---- Replied Message ----
| From | Shaun ***@***.***> |
| Date | 06/29/2023 21:16 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [rmqtt/rmqtt] /mqtt/subscribe Not Found (Issue #25) |

Thank you, putting a existing client, it responds.
What is the purpose of this command? It does not block and wait for a publish, it replies 'true' to all topics.

**Comment by greenpdx** [comment]
Ok
