### ISSUE TITLE
集群部署，节点选举出现“Leader ID exception”

### ISSUE THREAD

**Issue by bodypumper** [rmqtt/rmqtt#33]
动作1：使用官方提供的docker-compose进行部署，并按流程依次操作。
动作2：通过curl "http://127.0.0.1:6066/api/v1/health/check"进行查看。
问题如下图所示：
<img width="906" alt="image" src="https://github.com/rmqtt/rmqtt/assets/44149782/061a5e35-b32b-4108-b059-3419df5ee27b">

目前的解决方法：手动停止上图中的“节点3”，然后再重新启动“节点3”。再次重复动作2，“status” 返回OK。
![image](https://github.com/rmqtt/rmqtt/assets/44149782/44ccccf6-94ec-4c4a-a1fb-bc0b665c49d1)

**Comment by rmqtt** [comment]
是的，集群在同一台机器上使用docker-compose.yaml配置集群是有这种情况，各节点单独启动正常。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年08月14日 17:12 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [rmqtt/rmqtt] 集群部署，节点选举出现“Leader ID exception” (Issue #33) |

动作1：使用官方提供的docker-compose进行部署，并按流程依次操作。
动作2：通过curl "http://127.0.0.1:6066/api/v1/health/check"进行查看。
问题如下图所示：


目前的解决方法：手动停止上图中的“节点3”，然后再重新启动“节点3”。再次重复动作2，“status” 返回OK。

**Comment by bodypumper** [comment]
> 集群在同一台机器上使用docker-compose.yaml配置集群是有这种情况，各节点单独启动正常。

那么在同一个机器上，通过多个虚拟机来部署节点。是否可以规避该问题？或者官方后续版本是否有解决方案？

**Comment by rmqtt** [comment]
暂时还没有在k8s部署实验过，出现“Leader ID exception" 问题的原因就是多个节点同时启动从而找不到Leader，然后都把自己转换为Leader导致，只要保证节点启动顺序，就不会有问题。您可以尝试在k8s部署试试，然后给我们分享一下您的操作经验。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年08月14日 17:30 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [rmqtt/rmqtt] 集群部署，节点选举出现“Leader ID exception” (Issue #33) |

集群在同一台机器上使用docker-compose.yaml配置集群是有这种情况，各节点单独启动正常。

那么在同一个机器上，通过多个虚拟机来部署节点。是否可以规避该问题？或者官方后续版本是否有解决方案？

**Comment by jvasile** [comment]
[Fossil comment by james]

[GitHub comment by ]

是的，集群在同一台机器上使用docker-compose.yaml配置集群是有这种情况，各节点单独启动正常。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年08月14日 17:12 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [rmqtt/rmqtt] 集群部署，节点选举出现“Leader ID exception” (Issue #33) |

动作1：使用官方提供的docker-compose进行部署，并按流程依次操作。
动作2：通过curl "http://127.0.0.1:6066/api/v1/health/check"进行查看。
问题如下图所示：


目前的解决方法：手动停止上图中的“节点3”，然后再重新启动“节点3”。再次重复动作2，“status” 返回OK。

**Comment by jvasile** [comment]
[Fossil comment by james]

[GitHub comment by bodypumper]

> 集群在同一台机器上使用docker-compose.yaml配置集群是有这种情况，各节点单独启动正常。

那么在同一个机器上，通过多个虚拟机来部署节点。是否可以规避该问题？或者官方后续版本是否有解决方案？
目前我这里主用的是k8s部署服务的。

**Comment by jvasile** [comment]
[Fossil comment by james]

[GitHub comment by ]

暂时还没有在k8s部署实验过，出现“Leader ID exception" 问题的原因就是多个节点同时启动从而找不到Leader，然后都把自己转换为Leader导致，只要保证节点启动顺序，就不会有问题。您可以尝试在k8s部署试试，然后给我们分享一下您的操作经验。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年08月14日 17:30 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [rmqtt/rmqtt] 集群部署，节点选举出现“Leader ID exception” (Issue #33) |

集群在同一台机器上使用docker-compose.yaml配置集群是有这种情况，各节点单独启动正常。

那么在同一个机器上，通过多个虚拟机来部署节点。是否可以规避该问题？或者官方后续版本是否有解决方案？
