### ISSUE TITLE
topic的问题

### ISSUE THREAD

**Issue by charliexp** [rmqtt/rmqtt#4]
在测试时发现，
1. 一个客户端订阅了topic(如：a/b/#) 后，代码改成订阅另一个topic(如A/c/#)
2. 这个客户端的clientid 是指定的，前后两次使用相同的clientid
3. 当客户端订阅topic (A/c/#)时会收到topic（a/b/#）的消息。
4. 如果客户端订阅topic (A/c/#)前unsubscribe( 'a/b/#'),再subscribe( 'A/c/#')，则功能正常。
感觉是订阅的topic被保留到服务器上，每次有相同的clientid连入，不管是否订阅之前的topic，都会推送之前订阅过的消息。

**Comment by rhello1999** [comment]
使用相同的clientid再次连接，上一会话中的订阅关系会转移到当前会话上来。

**Comment by rhello1999** [comment]
不管是否订阅之前的topic，都会推送之前订阅过的消息。
--------------------------------------------------------------------------
这种属于离线消息。如果不想保留上一次会话中的任何数据，可以在连接时设置clean_session为true

**Comment by charliexp** [comment]
但是重新订阅不是不同的topic，应该不能推送过来，除非再次订阅上次的topic

**Comment by rmqtt** [comment]
会话转移后只要服务器端存在订阅关系，客户端就会收到匹配的新消息，新连接上直接就能收到未过期的上次会话的离线消息



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年12月03日 09:13 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [rmqtt/rmqtt] topic的问题 (Issue #4) |

但是重新订阅不是不同的topic，应该不能推送过来，除非再次订阅上次的topic

**Comment by charliexp** [comment]
OK，好的，估计我理解有误
