### ISSUE TITLE
login does not correctly handle error HTTP response

### ISSUE THREAD

**Issue by timzaak** [rmqtt/rmqtt#43]
### RMQTT Docker Version
0.2.11
### HTTP Auth Response
POST http://dev.fornetcode.com/mqtt/auth

HTTP/1.1 400 Bad Request
Server: nginx/1.23.4
Date: Fri, 22 Sep 2023 15:10:24 GMT
Content-Type: text/plain;charset=utf-8
Content-Length: 18
Connection: keep-alive

.clientId(missing)

Log:
![image](https://github.com/rmqtt/rmqtt/assets/6149407/0b4f9c17-3314-43bd-9e19-fea220efc3b0)

Result:
mqtt 链接正常保持，没有被踢掉。 MQTT 应该关闭链接的

**Comment by rhello2999** [comment]
0.2.11及之后版本对auth-http认证插件整个流程做了重新梳理，认证结果: Ignore ，表示忽略此次认证，将继续执行后续认证链。如果认证失败，需要返回：deny 。具体可参考文档 [  HTTP AUTH/ACL ](https://github.com/rmqtt/rmqtt/blob/master/docs/zh_CN/auth-http.md)来开发http认证服务。

## 认证原理

RMQTT 在设备连接事件中使用当前客户端相关信息作为参数，向用户自定义的认证服务发起请求查询权限，通过返回的 HTTP 响应信息来处理认证请求。

- 认证成功：
  - API 返回 2xx 状态码且消息体为:allow
- 认证失败：
  - API 返回 2xx 状态码且消息体为:deny
  - API HTTP 请求失败，且deny_if_error配置等于:true
- 忽略认证：
  - API 返回 2xx 状态码且消息体为:ignore, 继续执行认证链。
  - API 返回 4xx/5xx 状态码将忽略消息体并判定结果为:ignore, 继续执行认证链。
  - API HTTP 请求失败，且deny_if_error配置等于:false, 判定结果为:ignore, 继续执行认证链。
- 超级用户：
  - 认证成功 且 响应头返回“X-Superuser: true”, 超级用户将跳过ACL授权。
  
响应示例：
```json
HTTP/1.1 200 OK
X-Superuser: true
Content-Type: text/plain
Content-Length: 5
Date: Wed, 07 Jun 2023 01:29:23 GMT

allow
```

**Comment by rhello2999** [comment]
最好不要使用0.2.11版本，会话恢复时有bug, 已经在0.2.12及之后版本已经修复。

**Comment by rhello2999** [comment]
应该是web-hook插件中配置的hook.log，并不是rmqtt.log

rmqtt-web-hook.toml
```
## Default urls, supports http and file protocols
#urls = ["file:///var/log/rmqtt/hook.log", "http://127.0.0.1:5656/mqtt/webhook"]
urls = ["file:///var/log/rmqtt/hook.log"]

```

**Comment by rmqtt** [comment]
不能，如果是用相对路径，那参照的就是当前目录



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年09月24日 21:42 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [rmqtt/rmqtt] login does not correctly handle error HTTP response (Issue #43) |

补充一下， 设定的加载插件配置目录 plugins.dir="plugin/"，这个相对路径能否依据rmqtt.toml 的绝对路径来推导。
