### ISSUE TITLE
how to only provide tls external port

### ISSUE THREAD

**Issue by timzaak** [rmqtt/rmqtt#46]
当注释掉 `listener.tcp.external.addr = "0.0.0.0:1883"` 打开 `listener.tls.external.addr = "0.0.0.0:8883"`

报错：

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ConfigError(missing field `addr`)', /home/try/workspace/rmqtt/rmqtt/src/settings/mod.rs :100  :42

docker image 版本：0.2.16

**Comment by rhello2999** [comment]
要么把listener.tcp相关的所有配置注释，要么添加：listener.tcp.external.enable = false, 不能即有：listener.tcp相关其它配置，又不指定监听地址。

**Comment by rmqtt** [comment]
可以针对tls添加其它配置，比如：
listener.tls.external.workers
listener.tls.external.max_connections
并不是把listener.tcp直接改为listener.tls，这样改虽然也没错，但如果你需要tcp的时候又改回去不是很累，直接使用 listener.tcp.external.enable = false 开关控制吧。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年10月13日 15:56 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [rmqtt/rmqtt] how to only provide tls external port (Issue #46) |

是不是需要将
listener.tcp.external.workers
listener.tcp.external.max_connections
...
全部改成：
listener.tls.external.workers
listener.tls.external.max_connections
…
