### ISSUE TITLE
question: plugin usage

### ISSUE THREAD

**Issue by CoddingApe** [rmqtt/rmqtt#47]
hi there

how can i find and use some plugin such as rmqtt-sys-topic ?

**Comment by rmqtt** [comment]
Hello, configure in 'rmqtt. toml', such as:
##--------------------------------------------------------------------
## Plugins
##--------------------------------------------------------------------
#Plug in configuration file directory
plugins.dir = "rmqtt-plugins/"
#Plug in started by default, when the mqtt server is started
plugins.default_startups = [
   #"rmqtt-retainer",
   #"rmqtt-auth-http",
   #"rmqtt-cluster-broadcast",
   #"rmqtt-cluster-raft",
   #"rmqtt-http-api",
   #"rmqtt-sys



---- Replied Message ----
| From | ***@***.***> |
| Date | 10/24/2023 01:33 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [rmqtt/rmqtt] question: plugin usage (Issue #47) |

hi there

how can i find and use some plugin such as rmqtt-sys-topic ?

**Comment by CoddingApe** [comment]
i add rmqtt-sys-topic in etc/rmqtt.toml

plugins.default_startups = [
#    "rmqtt-cluster-broadcast"
#    "rmqtt-cluster-raft"
#    "rmqtt-auth-http",
#    "rmqtt-retainer",
#    "rmqtt-web-hook",
    "rmqtt-http-api",
    "rmqtt-sys-topic"
]

and add a file etc/plugins/rmqtt-sys-topic.toml with content

$ cat etc/plugins/rmqtt-sys-topic.toml
##--------------------------------------------------------------------
## rmqtt-sys-topic
##--------------------------------------------------------------------

#$SYS system message publish QoS
publish_qos = 1

#$SYS system message publish period
publish_interval = "1m"

but my mqtt client can not receive any event from $SYS topics  :(
is there any way to find out why ?

**Comment by rmqtt** [comment]
Please review the 'rmqtt-acl.toml' configuration. By default, the 'rmqtt-acl' plugin is enabled, and only connections from the 'dashboard' user or with a client IP of '127.0.0.1' are allowed to subscribe to the '$SYS/#' topic.

Default 'rmqtt-acl.toml' configuration:
```
rules = [
    ["allow", { user = "dashboard" }, "subscribe", ["$SYS/#"]],
    ["allow", { ipaddr = "127.0.0.1" }, "pubsub", ["$SYS/#", "#"]],
    ["deny", "all", "subscribe", ["$SYS/#", { eq = "#" }]],
    ["allow", "all"]
]
```

**Comment by CoddingApe** [comment]
well i figure it out, my fault.
i changed rmqtt from 0.2.12 to the latest version 0.2.19 and sys topics works.
thanks a lot for your amazing project !
