### ISSUE TITLE
Creating Clients

### ISSUE THREAD

**Issue by santiagz** [rmqtt/rmqtt#5]
Hello, I cannot understand how the mechanism of authorization through HTTP Auth is implemented.

I did not find in the documentation how to add usernames and passwords for clients, and the plugin description uses the path like `http://127.0.0.1:8080/mqtt/superuser`, which does not work...

can you tell me how to create users?

**Comment by rhello2999** [comment]
> Hello, I cannot understand how the mechanism of authorization through HTTP Auth is implemented.
> 
> I did not find in the documentation how to add usernames and passwords for clients, and the plugin description uses the path like `http://127.0.0.1:8080/mqtt/superuser`, which does not work...
> 
> can you tell me how to create users?

You need to prepare the HTTP API service for Auth verification. The APIs that need to be implemented are:
/mqtt/auth
/mqtt/superuser
/mqtt/acl

Request parameter reference: https://github.com/rmqtt/rmqtt/blob/master/rmqtt-plugins/rmqtt-auth-http.toml
Response parameters: If the status code returns 200, the verification is successful; if you need to cache the result, please return the string **ignore** in the Body.

**Comment by santiagz** [comment]
oooh i got it,  i'll try it 

thanks so much for the help
