### ISSUE TITLE
Max QOS in Connect ACK Protocol Question ? max_qos_allowed=2 Produce MQTT 5 Protocol Error ?

### ISSUE THREAD

**Issue by gajanak** [rmqtt/rmqtt#54]
Hi,

on fast testing I noticed perhaps a little Bug ?

Reading MQTT Spec CONNACK Properties:

https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901084

> 
> 3.2.2.3.4 Maximum QoS
> 
> 36 (0x24) Byte, Identifier of the Maximum QoS.
> 
> Followed by a Byte with a value of either 0 or 1. It is a Protocol Error to include Maximum QoS more than once, or to have a value other than 0 or 1. If the Maximum QoS is absent, the Client uses a Maximum QoS of 2.
> 

Could it be that the Sevrer in Version 0.3  send the configured  max_qos_allowed=2 properties which is a spec validation ?

Reproduced with latest Release , unchanged configuration, and Using a mqtt client which check this violation.

**Comment by rhello2999** [comment]
Hello, can you describe your testing process in detail? I will try to reproduce it.

**Comment by rhello2999** [comment]
> I used latest release (0.0.3) windows binary with default config. Tried to connect with for sample: https://github.com/dotnet/MQTTnet I don't know which other client will check the part of the Specification ;)
> 
> The Specification says that the Property 0x25 - Maximum QOS should only be on the connect ACK packet if its NOT 2. And if I look at the code - it sems its added always with value 2. Property is only present in ProtocolVersion 5.0.
> 
> You can alternative use this mqtt client: https://hivemq.github.io/mqtt-cli/docs/installation/
> 
> ```
> mqtt-cli.exe test
> MQTT 3: OK
>         - Maximum topic length: 65535 bytes
>         - QoS 0: Received 10/10 publishes in 5,54ms
>         - QoS 1: Received 10/10 publishes in 7,89ms
>         - QoS 2: Received 10/10 publishes in 12,21ms
>         - Retain: OK
>         - Wildcard subscriptions: OK
>         - Shared subscriptions: OK
>         - Payload size: >= 100000 bytes
>         - Maximum client id length: 65535 bytes
>         - Unsupported Ascii Chars: ALL SUPPORTED
> MQTT 5: Could not connect MQTT 5 client - Exception while decoding CONNACK: wrong maximum Qos
> ```
> 
> Does this help ?
This is very helpful to me and have reproduced the issue and it will be fixed in the next version. Thank you for submitting this issue.

**Comment by rmqtt** [comment]
Hello, this problem has been fixed in version 0.4.0.
