### ISSUE TITLE
Question/Request

### ISSUE THREAD

**Issue by akrizs** [rmqtt/rmqtt#55]
Hiya! again amazing server, is there any way of configuring rmqtt as a broker bridge to communicate/proxy messages across brokers?

Thanks!

**Comment by rmqtt** [comment]
Hello, thank you for your interest in rmqtt, this feature is not yet supported.



---- Replied Message ----
| From | Anton ***@***.***> |
| Date | 03/17/2024 05:49 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [rmqtt/rmqtt] Question/Request (Issue #55) |

Hiya! again amazing server, is there any way of configuring rmqtt as a broker bridge to communicate/proxy messages across brokers?

Thanks!

**Comment by rmqtt** [comment]
Starting from version 0.5.0, the "rmqtt-bridge-ingress-mqtt" and "rmqtt-bridge-egress-mqtt" plugins are supported.
