### ISSUE TITLE
WebSocket cannot connect

### ISSUE THREAD

**Issue by fikersd** [rmqtt/rmqtt#57]

**Comment by rmqtt** [comment]
Hello, can you provide a detailed description of your usage? I tested WS locally using MQTTX and WSS is available.



---- Replied Message ----
| From | ***@***.***> |
| Date | 04/17/2024 12:23 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | Re: [rmqtt/rmqtt] WebSocket cannot connect (Issue #57) |

Closed #57 as completed.
