### ISSUE TITLE
能不能加一下websokect接口

### ISSUE THREAD

**Issue by saywol** [rmqtt/rmqtt#6]
试了下您的项目，觉得真好，只是我平时用是网页创建websokect来接收数据的，不知道能不能给加一下websokect的接口，急切期盼！可惜我不会rust，无法贡献自己的力量

**Comment by rmqtt** [comment]
感谢您对rmqtt的认可，我这几天也正在考虑这个功能，但这个项目严重依赖ntex-mqtt，但又对它做了非常大的修改，已经不能方便的升级到它的最新版本。我再研究下如何做！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年02月20日 10:54 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [rmqtt/rmqtt] 能不能加一下websokect接口 (Issue #6) |

试了下您的项目，觉得真好，只是我平时用是网页创建websokect来接收数据的，不知道能不能给加一下websokect的接口，急切期盼！可惜我不会rust，无法贡献自己的力量

**Comment by tryor** [comment]
您好，在v0.2.10版本中已经支持WebSocket！

**Comment by rhello2999** [comment]
您好，0.2.10版本中已经支持WebSocket！

**Comment by saywol** [comment]
谢谢，果然更新了，没有白关注，明天我就现场环境试试去
