### ISSUE TITLE
CORS error when i make a request in react application with axios

### ISSUE THREAD

**Issue by darixsamani** [rmqtt/rmqtt#65]
I'm encountering an issue when attempting to access the HTTP REST API - the server is responding with a CORS error. I am using axios to make the request in my React application.

 Interestingly, when I try the same request using curl, it works perfectly fine.

![image](https://github.com/rmqtt/rmqtt/assets/67915678/b6093cd1-2bc7-48cb-9d62-95914dd9d82a)

**Comment by rmqtt** [comment]
CORS problem? It is recommended to access the rmqtt api through an http gateway that supports cross-domain functionality.



---- Replied Message ----
| From | Darix SAMANI ***@***.***> |
| Date | 06/08/2024 20:26 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [rmqtt/rmqtt] CORS error when i make a request in react application with axios (Issue #65) |

I'm encountering an issue when attempting to access the HTTP REST API - the server is responding with a CORS error. I am using axios to make the request in my React application.

Interestingly, when I try the same request using curl, it works perfectly fine.

image.png (view on web)

**Comment by darixsamani** [comment]
i have created a http api gateway with fastapi python), now it's work very well, thank you for your help

# example

[Capture vidéo du 08-06-2024 16:57:16.webm](https://github.com/rmqtt/rmqtt/assets/67915678/fe71766d-d06d-49e6-a86a-b0f2321780e6)
