### ISSUE TITLE
rmqtt 0.3.0  

### ISSUE THREAD

**Issue by uamself** [rmqtt/rmqtt#67]
When I use the rmqtt HTTP auth plugin, I must carry username or passrod to request a custom auth interface. If neither parameter is carried, the auth interface will not be used and the task authentication will be passed directly

**Comment by rhello2999** [comment]
Try turning off the anonymous switch.
Modify the default configuration of the 'rmqtt-acl' plugin, changing: ["allow", "all"] to ["deny", "all"].

**Comment by uamself** [comment]
If I do this, other normal users won't be able to use it anymore

**Comment by uamself** [comment]
The same issue also occurs in version 0.4.0

**Comment by uamself** [comment]
rmqtt-acl.toml  like this   ##--------------------------------------------------------------------
## rmqtt-acl
##--------------------------------------------------------------------

rules = [
    #["deny", "all", "subscribe", ["test/nosubscribe"]],
    #["allow", { user = "dashboard" }, "subscribe", ["$SYS/#"]],
    #["allow", { ipaddr = "127.0.0.1" }, "all", ["$SYS/#", "#"]],
    ["deny", "all", "subscribe", ["$SYS/#", { eq = "#" }]],
    ["allow", "all"],
    ["deny", {user="",password=""},"connect"]
]

but it does not work

**Comment by rhello2999** [comment]
rules = [
#["deny", "all", "subscribe", ["test/nosubscribe"]],
#["allow", { user = "dashboard" }, "subscribe", ["$SYS/#"]],
#["allow", { ipaddr = "127.0.0.1" }, "all", ["$SYS/#", "#"]],
["deny", "all", "subscribe", ["$SYS/#", { eq = "#" }]],
["deny", "all"],
]
