### ISSUE TITLE
[Feature] Configuration of available  MQTT protocol versions in server (3.1/5)

### ISSUE THREAD

**Issue by gajanak** [rmqtt/rmqtt#68]
Hi,

is there already a way to configure the server to use/allow ONLY 3.1 or ONLY V5 Mqtt protocol ?

Make it sense to have a listener configuration option for this ?

Perhaps a ACL Rule is a nice feature enhancments, to allow special clients to connect only with 3.1 or only with 5.

What is your opinion to this ?

**Comment by rmqtt** [comment]
This feature is now available in version 0.6.0.
