### ISSUE TITLE
Can't update package on windows and missing authentication.

### ISSUE THREAD

**Issue by Capiten** [rmqtt/rmqtt#7]
Hi

Great package, and apparently the only package on R to work with mqtt messages on widows.
I'm trying to use its but i need to add an user and password for the host I'm giving to the mqtt_topic_subscribe function, but aparently there isnt that option on the 0.1.0 at least, and I can't update it.
Any idea what could be the reason for not being able to update on windows R studio to the current 0.2.10 ? 
I'm using the dtupdate package to try to update this.

Thank you.

Cheers, Luís Pereira.

**Comment by tryor** [comment]
Hello, the early version does not support Auth, and after v0.1.6, it supports http authentication, which is realized through the plug-in "rmqtt-auth-http". You need to implement a set of http api services, and implement the following interfaces:
/mqtt/auth
/mqtt/superuser
/mqtt/acl

It is recommended to use the latest version: v0.2.10

Thanks for using!

**Comment by rhello2999** [comment]
Hello, the early version does not support Auth, and after v0.1.6, it supports http authentication, which is realized through the plug-in "rmqtt-auth-http". You need to implement a set of http api services, and implement the following interfaces:
/mqtt/auth
/mqtt/superuser
/mqtt/acl

It is recommended to use the latest version: v0.2.10

Thanks for using!
