### ISSUE TITLE
Release 0.5.0 has the 0.4.1 Assets instead of the 0.5.0 version

### ISSUE THREAD

**Issue by xdadrm** [rmqtt/rmqtt#73]
Just a heads-up :

https://github.com/rmqtt/rmqtt/releases/tag/0.5.0

has the binaries for 0.4.1 instead of 0.5.0 as Assets and are therefore missing the ingress,egress bridge plugins I wanted to try:

[rmqtt-0.4.1-x86_64-pc-windows.zip](https://github.com/rmqtt/rmqtt/releases/download/0.5.0/rmqtt-0.4.1-x86_64-pc-windows.zip)
[rmqtt-0.4.1-x86_64-unknown-linux-musl.zip](https://github.com/rmqtt/rmqtt/releases/download/0.5.0/rmqtt-0.4.1-x86_64-unknown-linux-musl.zip)

Great project, looks very promising !

**Comment by rmqtt** [comment]
Thank you for specifying this error!
