### ISSUE TITLE
arm64 platform docker image support

### ISSUE THREAD

**Issue by lazyzyf** [rmqtt/rmqtt#74]

**Comment by rmqtt** [comment]
Later versions will support it, thank you for your interest in RMQTT.



---- Replied Message ----
| From | ***@***.***> |
| Date | 08/01/2024 01:13 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [rmqtt/rmqtt] arm64 platform docker image support (Issue #74) |

**Comment by rmqtt** [comment]
hello, see https://hub.docker.com/r/rmqtt/rmqtt/tags
