### ISSUE TITLE
How many devices can be online simultaneously in cluster mode?

### ISSUE THREAD

**Issue by worldlg** [rmqtt/rmqtt#76]

**Comment by rmqtt** [comment]
The number of devices that the cluster mode can support online simultaneously depends on several factors, including the server hardware configuration, the chosen clustering mode, and the number of nodes in the cluster.

For detailed performance metrics and benchmarks, please refer to the rmqtt benchmark testing report: [rmqtt Benchmark Testing](https://github.com/rmqtt/rmqtt/blob/master/docs/en_US/benchmark-testing.md).

**Comment by worldlg** [comment]
Thanks.Does it support device connections of over 100 million?
