### ISSUE TITLE
Does it support the Protobuf protocol?

### ISSUE THREAD

**Issue by worldlg** [rmqtt/rmqtt#79]
Does it support the Protobuf protocol?

**Comment by rhello2999** [comment]
First, thank you for your interest in RMQTT. However, I don't understand! Why does the MQTT Broker need to support the Protobuf protocol?

**Comment by worldlg** [comment]
Like this：  https://www.emqx.com/en/blog/how-to-publish-and-receive-protobuf-messages-within-mqtt

**Comment by rmqtt** [comment]
If the MQTT Broker does not need to intercept and process the message payload, then the encoding/decoding of the message is handled by the MQTT Client. The MQTT Broker does not care about the encoding format of the message.



---- Replied Message ----
| From | ***@***.***> |
| Date | 08/08/2024 13:22 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | Re: [rmqtt/rmqtt] Does it support the Protobuf protocol? (Issue #79) |

Like this： https://www.emqx.com/en/blog/how-to-publish-and-receive-protobuf-messages-within-mqtt

**Comment by worldlg** [comment]
> If the MQTT Broker does not need to intercept and process the message payload, then the encoding/decoding of the message is handled by the MQTT Client. The MQTT Broker does not care about the encoding format of the message.
> […](#)
> ---- Replied Message ---- | From | ***@***.***> | | Date | 08/08/2024 13:22 | | To | ***@***.***> | | Cc | ***@***.***> | | Subject | Re: [rmqtt/rmqtt] Does it support the Protobuf protocol? (Issue #79) | Like this： https://www.emqx.com/en/blog/how-to-publish-and-receive-protobuf-messages-within-mqtt — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

oh,Thanks.
