### ISSUE TITLE
In MQTT bridge mode, can the upstream MQTT broker subscribe to topics dynamically based on the client’s subscriptions?

### ISSUE THREAD

**Issue by worldlg** [rmqtt/rmqtt#80]
In MQTT bridge mode, can the upstream MQTT broker subscribe to topics dynamically based on the client’s subscriptions?

**Comment by rmqtt** [comment]
The 'remote.topic' in MQTT Bridge ingress mode can be configured with wildcards (#, +) to increase the versatility of incoming message subscriptions.
