### ISSUE TITLE
能支持apache pulsar桥接么

### ISSUE THREAD

**Issue by cosoc** [rmqtt/rmqtt#82]
业务增长需要pulsar桥接,跪求支持!

**Comment by rmqtt** [comment]
您好，Apache Pulsar吗？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月21日 09:20 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [rmqtt/rmqtt] 能支持pulse桥接么 (Issue #82) |

业务增长需要pulse桥接,跪求支持!

**Comment by cosoc** [comment]
是的,https://pulsar.apache.org/

**Comment by cosoc** [comment]
> 您好，Apache Pulsar吗？
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年08月21日 09:20 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***> | | 主题 | [rmqtt/rmqtt] 能支持pulse桥接么 (Issue #82) | 业务增长需要pulse桥接,跪求支持! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

对

**Comment by rmqtt** [comment]
您好，master主分支提交了”Apache Pulsar桥接-出口模式“插件，看看是否满足您们业务需求。
