### ISSUE TITLE
端口功能补充

### ISSUE THREAD

**Issue by cosoc** [rmqtt/rmqtt#89]
每个端口功能说明,目前是盲猜

**Comment by rmqtt** [comment]
您好，之后会完善相关文档，谢谢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年09月10日 11:35 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [rmqtt/rmqtt] 端口功能补充 (Issue #89) |

每个端口功能说明,目前是盲猜
