### ISSUE TITLE
roadmap: where the project go

### ISSUE THREAD

**Issue by timzaak** [rmqtt/rmqtt#9]
Firstly, thanks for your awesome job of this project.  I haved used it in my own project: fornet. 
But I'm wondering where the project go, it seems all things about MQTT protocol have implemented.

您好，感谢您做了如此好用的项目。MQTT 相关的协议都已经实现完毕了，它下一步要如何发展？

**Comment by rmqtt** [comment]
首先感谢您对RMQTT的关注与肯定，现正在收集大家对RMQTT之后开发方向的建议和意见，[跳转](https://github.com/rmqtt/rmqtt/issues/10)
